name = "caffeine"
version = "0.0.1"
description = "A simple hello world Gleam project"
licences = ["GPL-3.0"]

[dependencies]
glaml = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
