name: Build and Deploy Scribble Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: '8.17'

      - name: Build Documentation
        run: |
          cd docs
          raco scribble --html caffeine.scrbl
          mkdir -p ../_site
          cp caffeine.html ../_site/index.html
          cp *.css *.js *.png *.svg ../_site/ 2>/dev/null || true
          cp ../CNAME ../_site/ 2>/dev/null || true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
