name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test on Gleam ${{ matrix.gleam-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Last 5 Gleam versions. Probably should be a more dynamic way to do this.
        gleam-version: ["1.8.0", "1.9.0", "1.10.0", "1.11.0", "1.12.0"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup BEAM (Erlang + Gleam)
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        gleam-version: ${{ matrix.gleam-version }}
        
    - name: Cache Gleam dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/gleam
          build
        key: ${{ runner.os }}-gleam-${{ matrix.gleam-version }}-${{ hashFiles('manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-gleam-${{ matrix.gleam-version }}-
          ${{ runner.os }}-gleam-
          
    - name: Download dependencies
      run: gleam deps download
      
    - name: Compile
      run: gleam build
      
    - name: Run tests
      run: gleam test
